# Generated by Django 5.2.8 on 2025-12-02 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('204c4e92-8888-4a2c-bdbc-a70bdb360af8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
