# Generated by Django 5.2.8 on 2025-12-02 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('539157c1-2a31-4a55-9bc0-ffdd7994f023'), editable=False, primary_key=True, serialize=False),
        ),
    ]
