# Generated by Django 5.2.8 on 2025-12-21 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f83855ac-d850-4fe1-8efd-8ab906b5575c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
