"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)e3enoj+ajohc=2u7%9_%8$0a)2c*hja*8u$3ckjzdc&oyz1lr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    # My apps
    'accounts',
    'orders',
    'products',
    # Cloudinary storage
    "cloudinary_storage",
    "cloudinary",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database + Storage
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
import dj_database_url

DATABASE_URL = 'postgresql://neondb_owner:npg_XKEdoF9A4tyc@ep-sweet-voice-a1efun2h-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': os.getenv('DB_NAME', 'project1_shop_db'),
    #     'USER': os.getenv('DB_USER', 'postgres'),
    #     'PASSWORD': os.getenv('DB_PASSWORD', 'binhbaoan12'),
    #     'HOST': os.getenv('DB_HOST', 'localhost'),
    #     'PORT': os.getenv('DB_PORT', '5432'),
    # }
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL", DATABASE_URL),
        conn_max_age=600,
        ssl_require=True,  # Neon cần SSL
    )
    
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Django 5+ recommended storage configuration
STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

CLOUDINARY_STORAGE = {
    # Use proper env var names, with safe defaults for local dev
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME', 'dk7vma9yr'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY', '419395252892955'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', 'IAwHqzE8SH_cP3JX7ufT_a8JX_k'),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

# DRF Settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Simple JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Project1 Shop API',
    'DESCRIPTION': 'API documentation for Project1 E-commerce',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    
    # Tự động group API theo tags
    'TAGS': [
        {'name': 'Authentication', 'description': 'APIs liên quan đến đăng nhập, đăng ký, đăng xuất'},
        {'name': 'Users', 'description': 'Quản lý thông tin user và profile'},
        {'name': 'Shipping Addresses', 'description': 'Quản lý địa chỉ giao hàng'},
        {'name': 'Products', 'description': 'Quản lý sản phẩm'},
        {'name': 'Categories', 'description': 'Quản lý danh mục sản phẩm'},
        {'name': 'Product Images', 'description': 'Quản lý hình ảnh sản phẩm'},
        {'name': 'Cart', 'description': 'Quản lý giỏ hàng'},
        {'name': 'Orders', 'description': 'Quản lý đơn hàng'},
    ],
    
    # Sắp xếp operations theo method
    'SORT_OPERATIONS': True,
    
    # Enum naming
    'ENUM_NAME_OVERRIDES': {
        'OrderStatusEnum': 'orders.models.OrderStatus',
    },
}
