# Generated by Django 5.2.8 on 2025-12-02 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04a8402a-b2b0-4b63-868b-3276e1af96eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b7db297a-101d-41e7-8859-376b25e285d2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7524156-2494-4cfb-b5ef-1db4138eab8e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bf68e81-12f6-4d3d-8fbf-93811fa7f19d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
