# Generated by Django 5.2.8 on 2025-12-02 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_id_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('03f1336c-915e-4f11-b8de-a1745307ac25'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7454e93d-c02f-4787-a4af-b3161edc3d57'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('360b6c19-89d4-4c29-81b3-d7d8b40242f2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e05e8076-6777-4310-accd-a8fbf14a36dc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
