# Generated by Django 5.2.8 on 2025-12-02 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_id_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6634abf3-1537-4471-a492-3d716f5a86ac'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b8b0366-1b2e-4400-98cd-15f2aacd0280'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c6a7270-e122-4413-87f3-208e921ac710'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84f1a14d-a440-4ae8-b776-40b0d7fd5cf9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
