# Generated by Django 5.2.8 on 2025-12-02 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10addb7c-94e3-4f37-9422-9152bc2cd547'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f8573f15-9abd-4f7b-876c-608a01612ec8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ac399fc-6bed-4ea4-9ee6-a308922fc21d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91dc122d-2d25-4f02-b624-de486a8abb16'), editable=False, primary_key=True, serialize=False),
        ),
    ]
