# Generated by Django 5.2.8 on 2025-12-02 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parentId',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39d3e723-2351-4707-a103-586d1431282d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68c70038-73df-412c-bfc2-0793fb32b958'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5c587fb4-485c-40fc-8fe2-b410c6d37b24'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dacc5ca1-b8d7-4f09-ba5c-72d9284259e2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
