# Generated by Django 5.2.8 on 2025-12-02 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_parentid_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('708f77ee-40f2-4123-b5db-5b163d924647'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57f02d38-af67-4f03-8d88-92c427452722'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bc9c9e5e-2cbb-4d43-862d-35aa0f84ea30'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bc191a72-4c8c-431b-8f95-6bc7061b444b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
